### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by ASHIRIGB** [mcguffin/the-paste#47]
Hi,

After upgrading to the latest version, i get the following Javascript error on the debug console. Using Chrome, and WP version 6.3.1.

uploader.jsx:128 Uncaught (in promise) TypeError: e.getSource is not a function
    at uploader.jsx:128:24
    at Array.filter (<anonymous>)
    at F.Uploader.<anonymous> (uploader.jsx:127:57)
    at the-paste.js?ver=2.0.4:13:54580
    at Array.forEach (<anonymous>)
    at the-paste.js?ver=2.0.4:13:54549

I am trying to copy an image from another chrome page, and paste directly into the library. 

Edit, everything used to work fine on 1.1.2 using the exact same setup.

**Comment by mcguffin** [comment]
Hi @ASHIRIGB,
Mhmm, I can't reproduce this on a fresh WordPress install...
The file `uploader.jsx` does not look very familiar to me. Can you figure out the full path of that jsx-file?
Might be another plugin hooking into the media library...

**Comment by ASHIRIGB** [comment]
sorry i forgot to mention that I have been using the "Real Media Library" plugin, but since it worked fine with the previous version it completely escaped my mind. I have disabled that plugin files copied/pasted successfully which means its a conflict with the "[Real Media Library](https://wordpress.org/plugins/real-media-library-lite/)" plugin.
